---
- hosts: jenkins
  user: root
  roles:
    - role: java # https://github.com/vrischmann/ansible-role-java
  vars_files:
    - vars/jenkins.yml
  tasks:
    - name: Add jenkins apt-key
      apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present
    - name: Configure apt repository manually to get around missing source repository problem
      template: src=templates/root/etc/apt/sources.list.d/jenkins.list.j2 dest=/etc/apt/sources.list.d/jenkins.list owner=root group=root mode=0755
    - name: Install jenkins
      apt: pkg=jenkins update-cache=yes state=latest
    - include: tasks/cli.yml

# Configure security:
#   usermod -G shadow jenkins
#   service jenkins restart
#   http://jenkins.mwarkentin.com:8080/configureSecurity/
#   Enable security
#   Unix user/group database
#     Advanced: sshd
