---
# Handle plugins
# If Jenkins is installed or updated, wait for pulling the Jenkins CLI, assuming 10s should be sufficiant
- name: 10s delay while starting Jenkins
  wait_for: port=8080 delay=10
  tags:
    - jenkins
    - cli

# Create Jenkins CLI destination directory
- name: "Create Jenkins CLI destination directory: ${jenkins.dest}"
  file: path=${jenkins.dest} state=directory
  tags:
    - jenkins
    - cli

# Get Jenkins CLI from localhost
- name: Get Jenkins CLI
  get_url: url=${jenkins.base_url}/jnlpJars/jenkins-cli.jar dest=${jenkins.cli_dest} mode=0440
  tags:
    - jenkins
    - cli

# Get latest Jenkins update file
- name: Get Jenkins updates
  get_url: url=http://updates.jenkins-ci.org/update-center.json dest=${jenkins.updates_dest} thirsty=yes mode=0440
  register: jenkins_updates
  tags:
    - jenkins
    - cli

# Jenkins Update-center
- name: Update-center Jenkins
  shell: "cat ${jenkins.updates_dest} | sed '1d;$d' | curl -X POST -H 'Accept: application/json' -d @- http://localhost:8080/updateCenter/byId/default/postBack"
  when: ${jenkins_updates.changed}
  tags:
    - jenkins
    - cli
