---
jenkins:
  repo: 'deb http://pkg.jenkins-ci.org/debian binary/' # Jenkins repository
  key: 'http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key' # Jenkins key
  base_url: 'http://jenkins.mwarkentin.com:8080'
  dest: '/opt/jenkins'
  cli_dest: '${jenkins.dest}/jenkins-cli.jar' # Jenkins CLI destination
  updates_dest: '${jenkins.dest}/updates_jenkins.json' # Jenkins updates file
  plugins:
    - 'git'
    - 'github'
    - 'github-api'
    - 'ghprb'
